use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum Operator {
    None,
    Delete,
    Yank,
    Change,
    ToUpper,
    ToLower,
    SwapCase,
    Indent,
    Outdent,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Motion {
    Left,
    Right,
    Up,
    Down,
    LineStart,
    LineEnd,
    LineFirstChar,
    LineLastChar,
    LineMiddle,
    BufferStart,
    BufferEnd,
    BufferByteOffset,
    WordForward,
    WordForwardBlank,
    WordForwardEnd,
    WordForwardEndBlank,
    WordBackward,
    WordBackwardBlank,
    WordBackwardEnd,
    WordBackwardEndBlank,
    WordBack,
    SentenceForward,
    SentenceBackward,
    ParagraphForward,
    ParagraphBackward,
    SectionForward,
    SectionBackward,
    SectionEndForward,
    SectionEndBackward,
    BraceForward,
    BraceBackward,
    ParenForward,
    ParenBackward,
    DiagnosticForward,
    DiagnosticBackward,
    NextChange,
    PrevChange,
    SearchForward(String),
    WindowTop,
    WindowMiddle,
    WindowBottom,
}

impl Motion {
    pub fn is_inclusive(&self) -> bool {
        match self {
            Motion::WordForwardEnd | Motion::WordForwardEndBlank |
            Motion::WordBackwardEnd | Motion::WordBackwardEndBlank |
            Motion::LineEnd | Motion::LineLastChar |
            Motion::BufferEnd => true,
            _ => false,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum TextObject {
    Word,
    BigWord,
    Sentence,
    Paragraph,
    Paren,
    Bracket,
    Brace,
    AngleBracket,
    Tag,
    Quote,
    DoubleQuote,
    Backtick,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum MouseButton {
    Left,
    Middle,
    Right,
    WheelUp,
    WheelDown,
    None,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum MouseAction {
    Press,
    Release,
    Drag,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Request {
    SetMode(crate::nvim::state::Mode),
    SetVisualMode(crate::nvim::state::VisualMode),
    CursorMove { row: usize, col: usize },
    InsertChar(char),
    InsertModeDeleteWord,
    InsertModeDeleteLine,
    DeleteCharAtCursor,
    DeleteLine,
    DeleteCurrentLine,
    Backspace,
    NewLine,
    InsertAtLastInsert,
    InsertAtFirstColumn,
    ReplaceCharUnderCursor(char),
    Undo,
    Redo,
    YankLine,
    Paste,
    PasteBefore,
    CmdLineChar(char),
    CmdLineBackspace,
    CmdLineTab,
    CmdLineDeleteWord,
    CmdLineDeleteLine,
    CmdLineMoveCursor { offset: i32 },
    CmdLineMoveCursorTo { pos: usize },
    CmdLineHistory { forward: bool },
    ExecuteCommand,
    ExecuteCommandFromConfig(String),
    ExecuteSearch,
    SearchWordUnderCursor { forward: bool, whole_word: bool },
    SearchNext { forward: bool },
    OpenLine { below: bool },
    OpMotion { op: Operator, motion: Motion },
    OpTextObject { op: Operator, inner: bool, obj: TextObject },
    OpVisualSelection(Operator),
    RestoreVisualSelection,
    SelectSearchMatch { forward: bool },
    StartMacroRecord(char),
    StopMacroRecord,
    PlayMacro(char),
    SaveShaDa(String),
    LoadShaDa(String),
    SaveUndo(String),
    LoadUndo(String),
    SaveSession(String),
    LoadSession(String),
    FormatRange { start_row: usize, end_row: usize },
    ComputeFolds,
    Indent { forward: bool },
    RepeatLastChange,
    BlockInsert { append: bool },
    SplitWindow { vertical: bool },
    NewTabPage,
    NextWindow,
    PrevWindow,
    OpenFloatWin { buf_id: i32, row: i32, col: i32, width: i32, height: i32 },
    MouseEvent { button: MouseButton, action: MouseAction, row: usize, col: usize },
    Resize { width: usize, height: usize },
    OpenFile(String),
    AlternateFile,
    SaveFile(Option<String>),
    SaveAll,
    Quit,
    QuitAll,
    Redraw,
    JumpToPair,
    ShowPum(Vec<String>),
    HidePum,
    SelectPumNext,
    SelectPumPrev,
    TriggerCompletion { forward: bool },
    CommitCompletion,
    JobStart(String),
    OpenTerminal(String),
    LspStart(String),
    TreesitterParse,
    RepeatLastCharSearch,
    JumpBack,
    JumpForward,
    MoveWord { forward: bool, end: bool },
    JumpToLineBoundary { end: bool },
    JumpToBufferBoundary { end: bool },
    FindChar { forward: bool, target: char, till: bool },
    ReplaceChar(char),
    SetMark(char),
    JumpToMark(char),
    SetRegister { reg: char, text: String },
    SwitchCase,
    Scroll { lines: i32 },
    CenterCursor,
    CursorToTop,
    CursorToBottom,
    CursorToTopWithCR,
    CursorToCenterWithDot,
    CursorToBottomWithMinus,
    IncrementNumber { offset: i32 },
    InsertCopyFromLine { offset: i32 },
}
